import { useQuery } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, BarChart3, Box, Loader2, RefreshCw } from 'lucide-react'
import { api } from '@/api/client'
import { getStoredAuth } from '@/auth'
import { formatPrice } from '@/utils/helpers'
import type { SmartVaultAsset, SmartVaultSummary } from '@/types'

export function SmartVaultPanel() {
  const navigate = useNavigate()
  const userId = getStoredAuth()?.user.id || ''
  const summaryQuery = useQuery<SmartVaultSummary>({ queryKey: ['smart-vault', 'summary'], queryFn: api.getVaultSummary, enabled: Boolean(userId) })
  const assetsQuery = useQuery<SmartVaultAsset[]>({ queryKey: ['smart-vault', 'assets', userId], queryFn: () => api.getVaultAssets(userId), enabled: Boolean(userId) })
  const alertsQuery = useQuery({ queryKey: ['smart-vault', 'alerts', userId], queryFn: () => api.getVaultAlerts(userId), enabled: Boolean(userId) })
  if (summaryQuery.isLoading || assetsQuery.isLoading) return <div className="card flex min-h-48 items-center justify-center gap-3" role="status"><Loader2 className="h-6 w-6 animate-spin text-amber-700" aria-hidden="true" />در حال دریافت خزانه هوشمند…</div>
  if (summaryQuery.isError || assetsQuery.isError) return <div className="card flex flex-col items-center gap-3 p-8 text-center"><AlertTriangle className="h-8 w-8 text-amber-700" aria-hidden="true" /><p className="font-bold">دریافت دارایی‌ها ناموفق بود</p><button type="button" className="btn btn-outline min-h-11 gap-2" onClick={() => { void summaryQuery.refetch(); void assetsQuery.refetch() }}><RefreshCw className="h-4 w-4" aria-hidden="true" />تلاش دوباره</button></div>
  const summary = summaryQuery.data || { assetCount: 0, purchaseValue: 0, currentValue: 0, goldWeight: 0, profitLoss: 0, profitLossPercent: 0 }
  const assets = assetsQuery.data || []
  return <section className="space-y-5" aria-labelledby="smart-vault-title"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow flex items-center gap-2"><Box className="h-4 w-4" aria-hidden="true" />دارایی‌های قابل رصد</p><h2 id="smart-vault-title" className="mt-2 text-2xl font-black">خزانه هوشمند</h2><p className="mt-2 text-sm leading-7 text-stone-600">ارزش خرید، ارزش فعلی و سود/زیان ثبت‌شده‌ی دارایی‌های شما.</p></div><span className="badge badge-success">{summary.assetCount} دارایی</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="ارزش فعلی" value={`${formatPrice(summary.currentValue)} تومان`} /><Metric label="ارزش خرید" value={`${formatPrice(summary.purchaseValue)} تومان`} /><Metric label="وزن طلا" value={`${summary.goldWeight.toLocaleString('fa-IR')} گرم`} /><Metric label="سود/زیان" value={`${summary.profitLoss >= 0 ? '+' : ''}${formatPrice(summary.profitLoss)} تومان`} tone={summary.profitLoss >= 0 ? 'positive' : 'negative'} /></div>{assets.length ? <div className="space-y-3">{assets.map((asset) => <article key={asset.id} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black">{asset.name}</h3><p className="mt-1 text-xs text-stone-500">{asset.category || 'دارایی طلا'} · {asset.weight} گرم · عیار {asset.karat}</p></div><div className="flex items-center gap-4 text-right sm:text-left"><div><p className="font-black">{formatPrice(asset.currentValue)} تومان</p><p className={`mt-1 text-xs font-semibold ${asset.profitLoss >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>{asset.profitLoss >= 0 ? '+' : ''}{formatPrice(asset.profitLoss)} ({asset.profitLossPercent.toFixed(2)}٪)</p></div><button type="button" className="btn btn-outline min-h-10 text-xs" onClick={() => navigate(`/auctions?tab=create&vaultAssetId=${encodeURIComponent(asset.id)}`)}>ثبت در بازار دست‌دوم</button></div></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-stone-300 p-8 text-center"><BarChart3 className="mx-auto h-8 w-8 text-stone-400" aria-hidden="true" /><p className="mt-3 font-bold">هنوز دارایی‌ای ثبت نشده</p><p className="mt-2 text-sm text-stone-600">پس از خرید یا ثبت دارایی، ارزش آن در خزانه نمایش داده می‌شود.</p></div>}{alertsQuery.data?.length ? <p className="text-xs text-stone-500" role="status">{alertsQuery.data.filter((alert) => alert.isActive).length} هشدار فعال برای پیگیری قیمت دارید.</p> : null}</section>
}
function Metric({ label, value, tone = 'default' }: { label: string; value: string; tone?: 'default' | 'positive' | 'negative' }) { return <div className="card p-4"><p className="text-xs text-stone-600">{label}</p><p className={`mt-2 text-lg font-black ${tone === 'positive' ? 'text-emerald-700' : tone === 'negative' ? 'text-red-700' : 'text-stone-950'}`}>{value}</p></div> }
