import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Heart, MessageCircle, Plus, Trophy } from 'lucide-react'
import { api } from '@/api/client'
import { getStoredAuth } from '@/auth'
import type { DesignChallenge, DesignComment, DesignPost } from '@/types'

export function CommunityPage() {
  const auth = getStoredAuth()
  const queryClient = useQueryClient()
  const posts = useQuery({ queryKey: ['community-posts'], queryFn: api.getCommunityPosts })
  const challenges = useQuery({ queryKey: ['community-challenges'], queryFn: api.getCommunityChallenges })
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const create = useMutation({ mutationFn: () => api.createCommunityPost({ title: title.trim(), description: description.trim() }), onSuccess: () => { setTitle(''); setDescription(''); void queryClient.invalidateQueries({ queryKey: ['community-posts'] }) } })
  const like = useMutation({ mutationFn: api.likeCommunityPost, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['community-posts'] }) })

  return <main className="bg-stone-50 pb-16 pt-24"><div className="container mx-auto max-w-7xl px-4"><header className="rounded-[2rem] bg-stone-950 p-6 text-white sm:p-10"><p className="eyebrow text-amber-300">GOLDEXA COMMUNITY</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">ایده‌هایتان را به نمایش بگذارید</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-stone-300">طرح‌های جواهر را ببینید، به سازندگان رأی بدهید و در چالش‌های طراحی Goldexa شرکت کنید.</p></header><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="space-y-5"><CreatePostForm auth={Boolean(auth)} title={title} description={description} setTitle={setTitle} setDescription={setDescription} onSubmit={() => create.mutate()} pending={create.isPending} error={create.isError} />{posts.isLoading ? <Loading /> : posts.isError ? <ErrorState onRetry={() => void posts.refetch()} /> : posts.data?.length ? posts.data.map((post) => <PostCard key={post.id} post={post} auth={Boolean(auth)} onLike={() => like.mutate(post.id)} liking={like.isPending} />) : <EmptyState />}</section><aside className="space-y-5"><section className="card p-5"><div className="flex items-center gap-3"><Trophy className="h-5 w-5 text-amber-700" aria-hidden="true" /><h2 className="font-black">چالش‌های فعال</h2></div>{challenges.isLoading ? <Loading /> : challenges.data?.filter((item) => item.status === 'active').length ? <div className="mt-4 space-y-3">{challenges.data.filter((item) => item.status === 'active').map((challenge) => <ChallengeCard key={challenge.id} challenge={challenge} />)}</div> : <p className="mt-4 text-sm text-stone-500">در حال حاضر چالش فعالی وجود ندارد.</p>}</section></aside></div></div></main>
}

function CreatePostForm({ auth, title, description, setTitle, setDescription, onSubmit, pending, error }: { auth: boolean; title: string; description: string; setTitle: (value: string) => void; setDescription: (value: string) => void; onSubmit: () => void; pending: boolean; error: boolean }) {
  return <section className="card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="rounded-2xl bg-amber-50 p-3 text-amber-700"><Plus className="h-5 w-5" aria-hidden="true" /></span><div><h2 className="font-black">طرح جدید منتشر کنید</h2><p className="mt-1 text-xs text-stone-500">توضیح کوتاه و شفاف به دیگران کمک می‌کند بهتر نظر بدهند.</p></div></div>{auth ? <form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); if (title.trim() && description.trim()) onSubmit() }}><label className="block text-sm font-bold" htmlFor="community-title">عنوان<input id="community-title" className="input mt-2" value={title} onChange={(event) => setTitle(event.target.value)} minLength={2} maxLength={160} required /></label><label className="block text-sm font-bold" htmlFor="community-description">توضیح<textarea id="community-description" className="input mt-2 min-h-24 py-3" value={description} onChange={(event) => setDescription(event.target.value)} minLength={2} maxLength={4000} required /></label><button className="btn btn-primary w-full" type="submit" disabled={pending || !title.trim() || !description.trim()}>{pending ? 'در حال انتشار…' : 'انتشار طرح'}</button>{error ? <p className="text-sm text-red-700" role="alert">انتشار طرح انجام نشد.</p> : null}</form> : <p className="mt-4 rounded-xl bg-stone-100 p-3 text-sm text-stone-600">برای انتشار طرح ابتدا وارد حساب شوید.</p>}</section>
}

function PostCard({ post, auth, onLike, liking }: { post: DesignPost; auth: boolean; onLike: () => void; liking: boolean }) {
  const [expanded, setExpanded] = useState(false)
  const [comment, setComment] = useState('')
  const comments = useQuery<DesignComment[]>({ queryKey: ['community-comments', post.id], queryFn: () => api.getCommunityComments(post.id), enabled: expanded })
  const addComment = useMutation({ mutationFn: () => api.addCommunityComment(post.id, { userName: getStoredAuth()?.user.name || 'کاربر Goldexa', body: comment.trim() }), onSuccess: () => { setComment(''); void comments.refetch() } })
  return <article className="card p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-amber-700">{post.userName}</p><h2 className="mt-1 text-xl font-black">{post.title}</h2></div><time className="text-xs text-stone-400" dateTime={post.createdAt}>{post.createdAt ? new Date(post.createdAt).toLocaleDateString('fa-IR') : ''}</time></div>{post.imageUrl ? <img className="mt-4 max-h-80 w-full rounded-2xl object-cover" src={post.imageUrl} alt={`تصویر طرح ${post.title}`} loading="lazy" /> : null}<p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-stone-600">{post.description}</p><div className="mt-5 flex items-center gap-4 border-t border-stone-100 pt-4 text-sm text-stone-500"><button type="button" className="flex min-h-11 items-center gap-2 rounded-xl px-3 transition hover:bg-rose-50 hover:text-rose-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600" onClick={onLike} disabled={liking} aria-label={`پسندیدن طرح ${post.title}`}><Heart className="h-5 w-5" aria-hidden="true" />{post.likesCount}</button><button type="button" className="flex min-h-11 items-center gap-2 rounded-xl px-3 transition hover:bg-amber-50 hover:text-amber-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded}><MessageCircle className="h-5 w-5" aria-hidden="true" />{post.commentsCount} نظر</button></div>{expanded ? <div className="mt-4 border-t border-stone-100 pt-4">{comments.isLoading ? <p className="text-sm text-stone-500" role="status">در حال دریافت نظرها…</p> : comments.data?.length ? <div className="space-y-2">{comments.data.map((item) => <div key={item.id} className="rounded-xl bg-stone-50 p-3 text-sm"><strong>{item.userName}</strong><p className="mt-1 text-stone-600">{item.body}</p></div>)}</div> : <p className="text-sm text-stone-500">هنوز نظری ثبت نشده است.</p>}{auth ? <form className="mt-3 flex gap-2" onSubmit={(event) => { event.preventDefault(); if (comment.trim()) addComment.mutate() }}><input className="input min-w-0 flex-1" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="نظر شما…" aria-label={`نظر درباره ${post.title}`} maxLength={1000} /><button className="btn btn-primary" type="submit" disabled={addComment.isPending || !comment.trim()}>ثبت</button></form> : null}{addComment.isError ? <p className="mt-2 text-sm text-red-700" role="alert">ثبت نظر انجام نشد.</p> : null}</div> : null}</article>
}

function ChallengeCard({ challenge }: { challenge: DesignChallenge }) { return <article className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-black text-stone-900">{challenge.title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{challenge.description}</p><p className="mt-3 text-xs text-amber-800">موضوع: {challenge.theme}</p></article> }
function Loading() { return <div className="card p-6 text-sm text-stone-500" role="status">در حال دریافت…</div> }
function ErrorState({ onRetry }: { onRetry: () => void }) { return <div className="card p-6 text-center"><p className="text-sm text-red-700">دریافت محتوا انجام نشد.</p><button type="button" className="btn btn-outline mt-3" onClick={onRetry}>تلاش دوباره</button></div> }
function EmptyState() { return <div className="card p-10 text-center text-sm text-stone-500">هنوز طرحی در جامعه منتشر نشده است.</div> }
