import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Bell, Clock3, CreditCard, Heart, Loader2, MapPin, Package, RefreshCw, Settings, ShieldCheck, User } from 'lucide-react'
import { api } from '@/api/client'
import { formatPrice, getStatusText } from '@/utils/helpers'
import { getStoredAuth } from '@/auth'
import type { Order, User as UserType } from '@/types'

const roleTitle: Record<UserType['role'], string> = { buyer: 'داشبورد خریدار', seller: 'داشبورد فروشنده', designer: 'داشبورد طراح', admin: 'داشبورد مدیریت', expert: 'داشبورد کارشناسی', premium: 'داشبورد کاربر ویژه', group_buyer: 'داشبورد خرید گروهی', customer: 'داشبورد کاربر' }
const tabs = [{ id: 'profile', label: 'پروفایل', icon: User }, { id: 'orders', label: 'سفارش‌ها', icon: Package }, { id: 'addresses', label: 'آدرس‌ها', icon: MapPin }, { id: 'wallet', label: 'کیف پول', icon: CreditCard }, { id: 'activity', label: 'فعالیت‌ها', icon: Clock3 }, { id: 'favorites', label: 'علاقه‌مندی‌ها', icon: Heart }, { id: 'notifications', label: 'اعلان‌ها', icon: Bell }, { id: 'settings', label: 'تنظیمات', icon: Settings }]

export function DashboardPage() {
  const navigate = useNavigate(); const auth = getStoredAuth(); const userId = auth?.user.id || ''; const [activeTab, setActiveTab] = useState('profile')
  const userQuery = useQuery({ queryKey: ['user', userId], queryFn: () => api.getUser(userId), enabled: Boolean(userId) }); const ordersQuery = useQuery({ queryKey: ['orders', 'user', userId], queryFn: () => api.getOrdersByUser(userId), enabled: Boolean(userId) }); const walletQuery = useQuery({ queryKey: ['wallet', userId], queryFn: () => api.getWallet(userId), enabled: Boolean(userId) }); const pricesQuery = useQuery({ queryKey: ['gold-prices'], queryFn: api.getGoldPrices, enabled: Boolean(userId) }); const transactionsQuery = useQuery({ queryKey: ['wallet-transactions', userId], queryFn: () => api.getWalletTransactions(userId), enabled: Boolean(userId) })
  const orders = useMemo(() => [...(ordersQuery.data || userQuery.data?.orders || [])].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [ordersQuery.data, userQuery.data?.orders])
  if (!userId) return <State title="ورود لازم است" description="برای مشاهده داشبورد ابتدا وارد حساب کاربری شوید." action={<button className="btn btn-primary" onClick={() => navigate('/login')}>ورود به حساب</button>} />
  if (userQuery.isLoading) return <Loading />
  if (userQuery.isError || !userQuery.data) return <State title="دریافت حساب ناموفق بود" description="اطلاعات حساب در دسترس نیست. دوباره تلاش کنید." action={<button className="btn btn-outline" onClick={() => { void userQuery.refetch(); void ordersQuery.refetch() }}><RefreshCw className="h-4 w-4" aria-hidden="true" />تلاش دوباره</button>} />
  const user = userQuery.data; const activeOrders = orders.filter((item) => ['pending', 'paid', 'processing', 'shipped'].includes(item.status)); const total = orders.reduce((sum, item) => sum + item.totalAmount, 0); const gold18 = pricesQuery.data?.find((item) => item.type === 'gold18')?.value
  return <main className="bg-stone-50 pb-16 pt-24"><div className="container mx-auto px-4"><div className="grid gap-6 lg:grid-cols-[250px_1fr]"><aside className="card h-fit p-5"><div className="border-b border-stone-200 pb-5 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-stone-900 text-3xl font-black text-amber-300">{user.name?.charAt(0) || 'گ'}</div><h2 className="mt-3 font-black">{user.name}</h2><p className="mt-1 text-sm text-amber-700">{roleTitle[user.role]}</p><p className="mt-1 text-xs text-stone-500">{user.phone}</p></div><nav className="mt-4 space-y-1" aria-label="منوی داشبورد">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setActiveTab(id)} aria-current={activeTab === id ? 'page' : undefined} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-right text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600 ${activeTab === id ? 'bg-amber-50 text-amber-800' : 'text-stone-600 hover:bg-stone-100'}`}><Icon className="h-5 w-5" aria-hidden="true" />{label}</button>)}{user.role === 'admin' && <button type="button" onClick={() => navigate('/admin')} className="flex min-h-11 w-full items-center gap-3 rounded-xl px-3 text-right text-sm font-semibold text-stone-600 hover:bg-stone-100"><ShieldCheck className="h-5 w-5" aria-hidden="true" />پنل مدیریت</button>}</nav></aside><section><header className="mb-6 rounded-3xl bg-stone-900 p-6 text-white sm:p-8"><p className="text-sm font-semibold text-amber-300">نمای کلی حساب</p><h1 className="mt-2 text-3xl font-black">{roleTitle[user.role]}</h1><p className="mt-3 text-sm leading-7 text-stone-300">اطلاعات حساب، سفارش‌ها و دارایی‌های شما در یک نگاه.</p></header><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="سفارش فعال" value={activeOrders.length.toString()} /><Metric label="مجموع خرید" value={`${formatPrice(total)} تومان`} /><Metric label="طلای دیجیتال" value={`${walletQuery.data?.goldBalanceGrams ?? 0} گرم`} /><Metric label="طلای ۱۸ عیار" value={gold18 ? `${formatPrice(gold18)} تومان` : 'در دسترس نیست'} /></div>{activeTab === 'profile' && <Profile user={user} />}{activeTab === 'orders' && <Orders orders={orders} />}{activeTab === 'addresses' && <Addresses addresses={user.addresses} />}{activeTab === 'wallet' && <WalletSummary wallet={walletQuery.data} />}{activeTab === 'activity' && <Activity transactions={transactionsQuery.data || []} />}{['favorites','notifications','settings'].includes(activeTab) && <EmptyPanel title={tabs.find((item) => item.id === activeTab)?.label || 'این بخش'} description="این بخش پس از اتصال قابلیت مربوطه به API نمایش داده خواهد شد." />}</section></div></div></main>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="card p-5"><p className="text-sm text-stone-600">{label}</p><p className="mt-2 text-xl font-black text-stone-950">{value}</p></div> }
function Profile({ user }: { user: UserType }) { return <Panel title="اطلاعات پروفایل"><div className="grid gap-4 sm:grid-cols-2"><ReadOnly label="نام و نام خانوادگی" value={user.name} /><ReadOnly label="شماره موبایل" value={user.phone} /><ReadOnly label="ایمیل" value={user.email || 'ثبت نشده'} /><ReadOnly label="سطح کاربری" value={user.level} /></div></Panel> }
function Orders({ orders }: { orders: Order[] }) { return <Panel title="آخرین سفارش‌ها">{orders.length ? <div className="space-y-3">{orders.slice(0, 8).map((order) => <div key={order.id} className="flex flex-col gap-3 rounded-2xl border border-stone-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{order.orderNumber || `#${order.id.slice(0, 8)}`}</p><p className="mt-1 text-xs text-stone-500">{getStatusText(order.status)} · {new Date(order.createdAt).toLocaleDateString('fa-IR')}</p></div><strong className="text-sm">{formatPrice(order.totalAmount)} تومان</strong></div>)}</div> : <EmptyPanel title="سفارشی ثبت نشده" description="پس از اولین خرید، سفارش شما اینجا نمایش داده می‌شود." />}</Panel> }
function Addresses({ addresses }: { addresses: UserType['addresses'] }) { return <Panel title="آدرس‌های شما">{addresses.length ? <div className="grid gap-4 sm:grid-cols-2">{addresses.map((address) => <div key={address.id} className="rounded-2xl border border-stone-200 p-4"><div className="flex justify-between gap-3"><strong>{address.title}</strong>{address.isDefault && <span className="badge badge-success">پیش‌فرض</span>}</div><p className="mt-3 text-sm leading-7 text-stone-600">{address.province}، {address.city}<br />{address.street}<br />کد پستی: {address.postalCode}</p></div>)}</div> : <EmptyPanel title="آدرسی ثبت نشده" description="آدرس ارسال شما پس از ثبت در این بخش نمایش داده می‌شود." />}</Panel> }
function WalletSummary({ wallet }: { wallet?: { balance: number; goldBalanceGrams: number } | null }) { return <Panel title="کیف پول"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-stone-900 p-5 text-white"><p className="text-sm text-stone-300">موجودی ریالی</p><p className="mt-2 text-2xl font-black">{formatPrice(wallet?.balance || 0)} تومان</p></div><div className="rounded-2xl bg-amber-50 p-5"><p className="text-sm text-stone-600">طلای دیجیتال</p><p className="mt-2 text-2xl font-black text-stone-950">{wallet?.goldBalanceGrams || 0} گرم</p></div></div></Panel> }
function Activity({ transactions }: { transactions: { id: string; type: string; amount: number; createdAt: string; description?: string | null }[] }) { return <Panel title="فعالیت‌های اخیر">{transactions.length ? <div className="space-y-3">{transactions.slice(0, 8).map((item) => <div key={item.id} className="flex justify-between gap-4 rounded-2xl border border-stone-200 p-4"><div><p className="font-bold">{item.type}</p><p className="mt-1 text-xs text-stone-500">{item.description || 'تراکنش کیف پول'}</p></div><div className="text-left"><strong>{item.amount} گرم</strong><time className="mt-1 block text-xs text-stone-500" dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleDateString('fa-IR')}</time></div></div>)}</div> : <EmptyPanel title="فعالیتی ثبت نشده" description="سوابق فعالیت مالی شما پس از اولین تراکنش نمایش داده می‌شود." />}</Panel> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card p-5 sm:p-7"><h2 className="mb-5 text-xl font-black">{title}</h2>{children}</div> }
function ReadOnly({ label, value }: { label: string; value: string }) { return <div><label className="mb-2 block text-xs text-stone-600">{label}</label><input value={value} readOnly className="input w-full" aria-label={label} /></div> }
function EmptyPanel({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-stone-300 bg-stone-50 p-10 text-center"><p className="font-bold">{title}</p><p className="mt-2 text-sm text-stone-600">{description}</p></div> }
function Loading() { return <div className="container mx-auto px-4 pb-16 pt-32"><div className="card flex min-h-64 items-center justify-center gap-3" role="status"><Loader2 className="h-8 w-8 animate-spin text-amber-700" aria-hidden="true" />در حال دریافت داشبورد…</div></div> }
function State({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="container mx-auto px-4 pb-16 pt-32"><div className="card mx-auto flex max-w-xl flex-col items-center gap-4 p-8 text-center"><ShieldCheck className="h-10 w-10 text-amber-700" aria-hidden="true" /><h1 className="text-2xl font-black">{title}</h1><p className="text-sm leading-7 text-stone-600">{description}</p>{action}</div></div> }
