import { FormEvent, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import type { Location } from 'react-router-dom'
import { LockKeyhole, ShieldCheck, Smartphone, UserCheck, Loader2, ArrowLeft } from 'lucide-react'
import { api } from '@/api/client'
import type { UserRole } from '@/types'

const roles: { value: UserRole; label: string }[] = [
  { value: 'buyer', label: 'خریدار' }, { value: 'seller', label: 'فروشنده' },
  { value: 'designer', label: 'طراح' }, { value: 'admin', label: 'مدیر سیستم' }, { value: 'expert', label: 'کارشناس' },
  { value: 'premium', label: 'کاربر ویژه' }, { value: 'group_buyer', label: 'خرید گروهی' },
]

export function LoginPage() {
  const navigate = useNavigate(); const location = useLocation()
  const [role, setRole] = useState<UserRole>('buyer'); const [phone, setPhone] = useState(''); const [otp, setOtp] = useState('')
  const [otpRequested, setOtpRequested] = useState(false); const [testOtp, setTestOtp] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState<'otp' | 'login' | null>(null)
  const redirectLocation = (location.state as { from?: Location } | null)?.from
  const normalizedPhone = phone.replace(/\D/g, '').slice(0, 11)

  async function requestOtp(event: FormEvent) { event.preventDefault(); if (normalizedPhone.length < 10) { setError('شماره موبایل را به‌صورت معتبر وارد کنید.'); return } setError(''); setTestOtp(''); setLoading('otp'); try { const response = await api.requestOtp(normalizedPhone, role); setTestOtp(response.otp || ''); setOtpRequested(true) } catch (e) { setError((e as { message?: string })?.message || 'ارسال کد ورود ناموفق بود.') } finally { setLoading(null) } }
  async function login(event: FormEvent) { event.preventDefault(); if (!otpRequested || otp.length < 4) { setError('ابتدا کد ارسال‌شده را وارد کنید.'); return } setError(''); setLoading('login'); try { const auth = await api.loginWithOtp(normalizedPhone, otp, role); const destination = redirectLocation?.pathname ? `${redirectLocation.pathname}${redirectLocation.search}${redirectLocation.hash}` : auth.user.role === 'admin' ? '/admin' : '/dashboard'; navigate(destination, { replace: true }) } catch (e) { setError((e as { message?: string })?.message || 'کد ورود معتبر نیست یا منقضی شده است.') } finally { setLoading(null) } }

  return <main className="min-h-screen bg-stone-950 px-4 py-10 text-stone-950 sm:py-16"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-[2rem] border border-white/10 bg-stone-50 shadow-2xl lg:grid-cols-[0.9fr_1.1fr]">
    <section className="relative overflow-hidden bg-stone-900 p-8 text-white sm:p-12"><div className="relative flex h-full flex-col justify-between gap-12"><div><div className="mb-8 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-600"><ShieldCheck className="h-6 w-6" aria-hidden="true" /></span><div><p className="text-sm text-amber-300">Goldexa</p><p className="font-semibold">ورود امن به دارایی شما</p></div></div><p className="mb-3 text-sm font-semibold text-amber-300">حساب شما، همیشه تحت کنترل شما</p><h1 className="max-w-md text-4xl font-black leading-tight sm:text-5xl">با اطمینان وارد بازار طلا شوید.</h1><p className="mt-5 max-w-md leading-8 text-stone-300">برای ورود، شماره موبایل خود را ثبت کنید. کد یک‌بارمصرف از مسیر امن حساب کاربری برای شما ارسال می‌شود.</p></div><div className="grid gap-3 text-sm text-stone-300 sm:grid-cols-2">{['احراز هویت دومرحله‌ای','حفاظت از تراکنش‌های مالی','دسترسی یکپارچه به سفارش‌ها','پشتیبانی از نقش‌های مختلف'].map((item) => <div key={item} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 p-3"><ShieldCheck className="h-4 w-4 text-amber-300" aria-hidden="true" />{item}</div>)}</div></div></section>
    <section className="p-6 sm:p-12" aria-labelledby="login-title"><div className="mx-auto max-w-md"><p className="text-sm font-semibold text-amber-700">ورود به حساب</p><h2 id="login-title" className="mt-2 text-3xl font-black tracking-tight">شروع امن و سریع</h2><p className="mt-3 text-sm leading-7 text-stone-600">شماره موبایل و نقش حساب خود را وارد کنید.</p><div className="mt-8 space-y-5">
      <form onSubmit={requestOtp} className="space-y-5" noValidate><div><label htmlFor="login-role" className="mb-2 block text-sm font-semibold">نوع حساب</label><select id="login-role" value={role} onChange={(e) => setRole(e.target.value as UserRole)} className="input w-full" disabled={loading !== null}>{roles.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><div><label htmlFor="login-phone" className="mb-2 block text-sm font-semibold">شماره موبایل</label><div className="relative"><Smartphone className="absolute right-3 top-1/2 h-5 w-5 -translate-y-1/2 text-stone-400" aria-hidden="true" /><input id="login-phone" value={phone} onChange={(e) => setPhone(e.target.value.replace(/\D/g, '').slice(0, 11))} className="input w-full pr-11" inputMode="tel" autoComplete="tel" placeholder="مثلاً ۰۹۱۲۱۲۳۴۵۶۷" required /></div><p className="mt-2 text-xs text-stone-500">شماره موبایل بدون فاصله وارد شود.</p></div><button type="submit" disabled={loading !== null} className="btn btn-primary flex min-h-11 w-full items-center justify-center gap-2">{loading === 'otp' && <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />}{loading === 'otp' ? 'در حال ارسال…' : 'دریافت کد ورود'}</button></form>
      {otpRequested && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900" role="status">کد ورود ارسال شد. کد دریافت‌شده را وارد کنید.{testOtp && <div className="mt-2 rounded-lg bg-white/70 px-3 py-2 text-center font-black tracking-[0.35em]" dir="ltr" aria-label="کد تست محیط توسعه">{testOtp}</div>}</div>}
      <form onSubmit={login} className="space-y-5 border-t border-stone-200 pt-5" noValidate><div><label htmlFor="login-otp" className="mb-2 block text-sm font-semibold">کد یک‌بارمصرف</label><div className="relative"><UserCheck className="absolute right-3 top-1/2 h-5 w-5 -translate-y-1/2 text-stone-400" aria-hidden="true" /><input id="login-otp" value={otp} onChange={(e) => setOtp(e.target.value.replace(/\D/g, '').slice(0, 6))} className="input w-full pr-11 text-center font-black tracking-[0.45em]" inputMode="numeric" autoComplete="one-time-code" maxLength={6} placeholder="••••••" required disabled={!otpRequested} /></div></div><button type="submit" disabled={loading !== null || !otpRequested || otp.length < 4} className="btn btn-secondary flex min-h-11 w-full items-center justify-center gap-2 disabled:cursor-not-allowed disabled:opacity-50">{loading === 'login' && <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />}{loading === 'login' ? 'در حال ورود…' : 'ورود به حساب'}</button></form>
    </div>{error && <p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm leading-6 text-red-800" role="alert">{error}</p>}<button type="button" onClick={() => navigate('/')} className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-stone-600 transition hover:text-amber-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600 focus-visible:ring-offset-2"><ArrowLeft className="h-4 w-4" aria-hidden="true" />بازگشت به صفحه اصلی</button><p className="mt-6 flex items-center gap-2 text-xs text-stone-500"><LockKeyhole className="h-4 w-4" aria-hidden="true" />اطلاعات ورود شما رمزنگاری و محافظت می‌شود.</p></div></section>
  </div></main>
}
