import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowDownUp, Coins, CreditCard, History, Loader2, RefreshCw, ShieldCheck } from 'lucide-react'
import { api } from '@/api/client'
import { formatPrice } from '@/utils/helpers'
import type { WalletTransaction } from '@/types'
import { getStoredAuth } from '@/auth'

export function WalletPage() {
  const userId = getStoredAuth()?.user.id || ''
  const [activeTab, setActiveTab] = useState<'summary' | 'transactions'>('summary')
  const [grams, setGrams] = useState('')
  const queryClient = useQueryClient()
  const walletQuery = useQuery({ queryKey: ['wallet', userId], queryFn: () => api.getWallet(userId), enabled: Boolean(userId), refetchInterval: 30000 })
  const transactionsQuery = useQuery({ queryKey: ['wallet-transactions', userId], queryFn: () => api.getWalletTransactions(userId), enabled: Boolean(userId) })
  const transactions = transactionsQuery.data ?? []
  const latestTransactions = transactions.slice(0, 8)
  const tradeMutation = useMutation({ mutationFn: ({ side, amountGrams }: { side: 'buy' | 'sell'; amountGrams: number }) => side === 'buy' ? api.buyWalletGold({ userId, amountGrams }) : api.sellWalletGold({ userId, amountGrams }), onSuccess: () => { setGrams(''); void queryClient.invalidateQueries({ queryKey: ['wallet', userId] }); void queryClient.invalidateQueries({ queryKey: ['wallet-transactions', userId] }) } })

  if (!userId) return <StateCard title="ورود لازم است" description="برای مشاهده کیف پول، ابتدا وارد حساب کاربری شوید." />
  if (walletQuery.isLoading || transactionsQuery.isLoading) return <LoadingState />
  if (walletQuery.isError || transactionsQuery.isError) return <StateCard title="دریافت کیف پول ناموفق بود" description="اتصال را بررسی کنید و دوباره تلاش کنید." action={<button className="btn btn-outline" onClick={() => { void walletQuery.refetch(); void transactionsQuery.refetch() }}><RefreshCw className="h-4 w-4" aria-hidden="true" />تلاش دوباره</button>} />

  const wallet = walletQuery.data
  return <main className="bg-stone-50 pb-16 pt-24"><div className="container mx-auto px-4"><header className="mb-8 flex flex-col gap-4 border-b border-stone-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-amber-700">کیف پول دیجیتال طلا</p><h1 className="mt-2 text-3xl font-black tracking-tight text-stone-950">مدیریت دارایی</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-stone-600">موجودی ریالی، طلای دیجیتال و تاریخچه تراکنش‌های مالی در یک نمای امن.</p></div><div className="flex gap-2" role="tablist" aria-label="بخش‌های کیف پول"><TabButton active={activeTab === 'summary'} onClick={() => setActiveTab('summary')} id="wallet-summary-tab">خلاصه</TabButton><TabButton active={activeTab === 'transactions'} onClick={() => setActiveTab('transactions')} id="wallet-transactions-tab">تراکنش‌ها</TabButton></div></header>
     <section className="grid gap-4 md:grid-cols-3" aria-label="خلاصه موجودی"><Metric icon={<CreditCard />} label="موجودی ریالی" value={`${formatPrice(wallet?.balance ?? 0)} تومان`} /><Metric icon={<Coins />} label="طلای دیجیتال" value={`${wallet?.goldBalanceGrams ?? 0} گرم`} /><Metric icon={<ArrowDownUp />} label="تعداد تراکنش" value={`${transactions.length} مورد`} /></section>
     <section className="card mt-6 p-5 sm:p-7" aria-labelledby="gold-trade-title"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 id="gold-trade-title" className="text-xl font-black text-stone-950">خرید و فروش طلای دیجیتال</h2><p className="mt-1 text-sm leading-7 text-stone-600">قیمت نهایی و اعتبار موجودی در سرور محاسبه می‌شود.</p></div><label className="text-sm font-semibold text-stone-700">مقدار به گرم<input value={grams} onChange={(event) => setGrams(event.target.value.replace(/[^0-9.]/g, ''))} className="input mt-2 w-full sm:w-48" inputMode="decimal" min="0.0001" step="0.0001" placeholder="مثلاً ۱.۵" aria-label="مقدار طلا به گرم" /></label></div><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="btn btn-primary min-h-11" disabled={tradeMutation.isPending || Number(grams) <= 0} onClick={() => tradeMutation.mutate({ side: 'buy', amountGrams: Number(grams) })}>{tradeMutation.isPending ? 'در حال پردازش…' : 'خرید طلا'}</button><button type="button" className="btn btn-outline min-h-11" disabled={tradeMutation.isPending || Number(grams) <= 0} onClick={() => tradeMutation.mutate({ side: 'sell', amountGrams: Number(grams) })}>فروش طلا</button></div>{tradeMutation.isError ? <p className="mt-3 text-sm text-red-700" role="alert">عملیات انجام نشد؛ موجودی و قیمت لحظه‌ای را بررسی کنید.</p> : null}{tradeMutation.isSuccess ? <p className="mt-3 text-sm text-emerald-700" role="status">تراکنش با موفقیت ثبت شد.</p> : null}</section>
    {activeTab === 'summary' ? <section className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_1fr]" aria-labelledby="latest-title"><div className="card p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><h2 id="latest-title" className="text-xl font-black text-stone-950">آخرین تراکنش‌ها</h2><p className="mt-1 text-sm text-stone-600">آخرین تغییرات ثبت‌شده در کیف پول</p></div><History className="h-5 w-5 text-amber-700" aria-hidden="true" /></div>{latestTransactions.length ? <div className="space-y-3">{latestTransactions.map((item) => <WalletTransactionRow key={item.id} transaction={item} />)}</div> : <EmptyState title="تراکنشی ثبت نشده است" description="بعد از خرید یا پرداخت با کیف پول، سوابق اینجا نمایش داده می‌شود." />}</div><SecurityCard /></section> : <section className="card p-5 sm:p-7" aria-labelledby="all-title"><h2 id="all-title" className="mb-5 text-xl font-black text-stone-950">تاریخچه کامل تراکنش‌ها</h2>{transactions.length ? <div className="space-y-3">{transactions.map((item) => <WalletTransactionRow key={item.id} transaction={item} />)}</div> : <EmptyState title="تراکنشی ثبت نشده است" description="هنوز تراکنشی برای حساب شما ثبت نشده است." />}</section>}
  </div></main>
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="card p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-50 text-amber-700">{icon}</span><div><p className="text-sm text-stone-600">{label}</p><p className="mt-1 text-xl font-black text-stone-950">{value}</p></div></div></div> }
function TabButton({ active, onClick, children, id }: { active: boolean; onClick: () => void; children: React.ReactNode; id: string }) { return <button id={id} type="button" role="tab" aria-selected={active} onClick={onClick} className={`btn min-h-11 ${active ? 'btn-primary' : 'btn-outline'}`}>{children}</button> }
 function WalletTransactionRow({ transaction }: { transaction: WalletTransaction }) { const positive = transaction.amount >= 0; const goldDelta = (transaction as WalletTransaction & { amountGrams?: number }).amountGrams; return <article className="flex flex-col gap-3 rounded-2xl border border-stone-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-2xl ${positive ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}><ArrowDownUp className="h-5 w-5" aria-hidden="true" /></span><div><p className="font-bold text-stone-950">{transaction.type || 'تراکنش کیف پول'}</p><p className="mt-1 text-xs text-stone-600">{transaction.description || 'تغییر موجودی حساب'}</p></div></div><div className="text-right sm:text-left"><p className={`font-black ${positive ? 'text-emerald-700' : 'text-red-700'}`}>{positive ? '+' : ''}{formatPrice(transaction.amount)} تومان</p>{goldDelta ? <p className="mt-1 text-xs text-stone-600">{goldDelta > 0 ? '+' : ''}{goldDelta} گرم طلا</p> : null}<time className="mt-1 block text-xs text-stone-500" dateTime={transaction.createdAt}>{new Date(transaction.createdAt).toLocaleString('fa-IR')}</time></div></article> }
function SecurityCard() { return <aside className="card p-5 sm:p-7"><h2 className="text-xl font-black text-stone-950">امنیت مالی</h2><div className="mt-5 space-y-3 text-sm leading-7 text-stone-600">{['تغییرات کیف پول به‌صورت تراکنش قابل ردیابی ثبت می‌شود.','موجودی طلای دیجیتال منفی نمی‌شود.','مبلغ واقعی همیشه از سرور خوانده می‌شود.'].map((text) => <div key={text} className="flex gap-3 rounded-2xl bg-stone-100 p-4"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-amber-700" aria-hidden="true" /><p>{text}</p></div>)}</div></aside> }
function LoadingState() { return <div className="container mx-auto px-4 pb-16 pt-32"><div className="card flex min-h-64 flex-col items-center justify-center gap-3" role="status"><Loader2 className="h-8 w-8 animate-spin text-amber-700" aria-hidden="true" /><p className="text-sm text-stone-600">در حال دریافت اطلاعات کیف پول…</p></div></div> }
function StateCard({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="container mx-auto px-4 pb-16 pt-32"><div className="card mx-auto flex max-w-xl flex-col items-center gap-4 p-8 text-center"><ShieldCheck className="h-10 w-10 text-amber-700" aria-hidden="true" /><h1 className="text-2xl font-black">{title}</h1><p className="text-sm leading-7 text-stone-600">{description}</p>{action}</div></div> }
function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-stone-300 bg-stone-50 p-10 text-center"><p className="font-bold text-stone-900">{title}</p><p className="mt-2 text-sm text-stone-600">{description}</p></div> }
